export const SUBJECTS = [
  {
    id: 'math',
    name: 'Mathematics',
    icon: '∑',
    color: '#1a3a5c',
    description: 'Algebra, Calculus, Trigonometry, Statistics and more.',
    topics: ['Algebra', 'Calculus', 'Trigonometry', 'Statistics', 'Geometry'],
    tests: 8,
    duration: '90 min',
    level: 'Intermediate',
  },
  {
    id: 'physics',
    name: 'Physics',
    icon: '⚛',
    color: '#2ea87e',
    description: 'Mechanics, Thermodynamics, Optics, Electromagnetism.',
    topics: ['Mechanics', 'Thermodynamics', 'Optics', 'Electromagnetism', 'Modern Physics'],
    tests: 7,
    duration: '90 min',
    level: 'Advanced',
  },
  {
    id: 'cs',
    name: 'Computer Science',
    icon: '⌨',
    color: '#7c3aed',
    description: 'Data Structures, Algorithms, OS, Networks, DBMS.',
    topics: ['DSA', 'Algorithms', 'Operating Systems', 'Networks', 'DBMS'],
    tests: 10,
    duration: '60 min',
    level: 'Intermediate',
  },
  {
    id: 'chem',
    name: 'Chemistry',
    icon: '⚗',
    color: '#e85d26',
    description: 'Organic, Inorganic, Physical Chemistry concepts.',
    topics: ['Organic', 'Inorganic', 'Physical', 'Electrochemistry', 'Thermochemistry'],
    tests: 6,
    duration: '75 min',
    level: 'Beginner',
  },
  {
    id: 'bio',
    name: 'Biology',
    icon: '🧬',
    color: '#059669',
    description: 'Cell biology, Genetics, Ecology, Human physiology.',
    topics: ['Cell Biology', 'Genetics', 'Ecology', 'Physiology', 'Evolution'],
    tests: 7,
    duration: '75 min',
    level: 'Beginner',
  },
  {
    id: 'english',
    name: 'English',
    icon: '✍',
    color: '#b45309',
    description: 'Grammar, Comprehension, Vocabulary and Writing.',
    topics: ['Grammar', 'Comprehension', 'Vocabulary', 'Writing', 'Literature'],
    tests: 5,
    duration: '60 min',
    level: 'Intermediate',
  },
];

export const MOCK_TESTS = [
  {
    id: 'mt1',
    subject: 'Mathematics',
    subjectId: 'math',
    title: 'Algebra Fundamentals',
    questions: 20,
    duration: 30,
    difficulty: 'Easy',
    attempts: 1204,
  },
  {
    id: 'mt2',
    subject: 'Mathematics',
    subjectId: 'math',
    title: 'Calculus – Limits & Derivatives',
    questions: 25,
    duration: 45,
    difficulty: 'Medium',
    attempts: 876,
  },
  {
    id: 'mt3',
    subject: 'Physics',
    subjectId: 'physics',
    title: 'Mechanics & Motion',
    questions: 20,
    duration: 30,
    difficulty: 'Easy',
    attempts: 943,
  },
  {
    id: 'mt4',
    subject: 'Physics',
    subjectId: 'physics',
    title: 'Electromagnetism Full Test',
    questions: 30,
    duration: 50,
    difficulty: 'Hard',
    attempts: 512,
  },
  {
    id: 'mt5',
    subject: 'Computer Science',
    subjectId: 'cs',
    title: 'Data Structures Basics',
    questions: 20,
    duration: 25,
    difficulty: 'Easy',
    attempts: 1567,
  },
  {
    id: 'mt6',
    subject: 'Computer Science',
    subjectId: 'cs',
    title: 'Sorting & Searching Algorithms',
    questions: 25,
    duration: 40,
    difficulty: 'Medium',
    attempts: 1102,
  },
  {
    id: 'mt7',
    subject: 'Chemistry',
    subjectId: 'chem',
    title: 'Organic Chemistry – Reactions',
    questions: 20,
    duration: 35,
    difficulty: 'Medium',
    attempts: 789,
  },
  {
    id: 'mt8',
    subject: 'Biology',
    subjectId: 'bio',
    title: 'Cell Biology & Genetics',
    questions: 20,
    duration: 30,
    difficulty: 'Easy',
    attempts: 934,
  },
];

export const SAMPLE_QUESTIONS = {
  math: [
    { q: 'What is the derivative of sin(x)?', options: ['cos(x)', '-cos(x)', '-sin(x)', 'tan(x)'], answer: 0 },
    { q: 'What is the value of lim(x→0) sin(x)/x?', options: ['0', '∞', '1', 'undefined'], answer: 2 },
    { q: 'Solve: 2x + 5 = 13', options: ['x = 3', 'x = 4', 'x = 9', 'x = 2'], answer: 1 },
    { q: 'Which is a quadratic equation?', options: ['x + 2 = 0', 'x² + 3x + 2 = 0', '2x = 6', '3x - 1 = 5'], answer: 1 },
    { q: 'What is log₁₀(1000)?', options: ['2', '3', '10', '100'], answer: 1 },
    { q: 'Find the sum of first 10 natural numbers.', options: ['45', '50', '55', '60'], answer: 2 },
    { q: 'What is the value of sin(90°)?', options: ['0', '1', '-1', 'undefined'], answer: 1 },
  ],
  physics: [
    { q: 'What is the SI unit of force?', options: ['Kilogram', 'Newton', 'Joule', 'Watt'], answer: 1 },
    { q: 'Which law states F = ma?', options: ['First Law', 'Second Law', 'Third Law', 'Zeroth Law'], answer: 1 },
    { q: 'What is the speed of light in vacuum?', options: ['3 × 10⁸ m/s', '3 × 10⁶ m/s', '3 × 10⁹ m/s', '3 × 10⁷ m/s'], answer: 0 },
    { q: 'What is the relationship between V, I, and R in Ohm\'s Law?', options: ['V = I/R', 'V = I × R', 'V = R/I', 'I = V/R'], answer: 1 },
    { q: 'What is the SI unit of energy?', options: ['Newton', 'Watt', 'Joule', 'Pascal'], answer: 2 },
    { q: 'Define acceleration.', options: ['Distance covered per unit time', 'Change in velocity per unit time', 'Force applied on object', 'Work done per unit time'], answer: 1 },
    { q: 'What is the value of gravitational acceleration (g)?', options: ['8.8 m/s²', '9.8 m/s²', '10.8 m/s²', '7.8 m/s²'], answer: 1 },
  ],
  cs: [
    { q: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], answer: 1 },
    { q: 'Which data structure uses LIFO principle?', options: ['Queue', 'Stack', 'Array', 'Tree'], answer: 1 },
    { q: 'What does SQL stand for?', options: ['Standard Query Language', 'Structured Query Language', 'Standard Question Language', 'Structured Question Language'], answer: 1 },
    { q: 'Which sorting algorithm has best average case?', options: ['Bubble Sort', 'Selection Sort', 'Quick Sort', 'Insertion Sort'], answer: 2 },
    { q: 'What is the main feature of OOP?', options: ['Procedural', 'Functional', 'Encapsulation', 'Linear'], answer: 2 },
    { q: 'What does API stand for?', options: ['Application Programming Interface', 'Advanced Programming Input', 'Application Process Input', 'Advanced Process Interface'], answer: 0 },
    { q: 'Which is not a programming paradigm?', options: ['Object-Oriented', 'Functional', 'Procedural', 'Numerical'], answer: 3 },
  ],
  chem: [
    { q: 'What is the atomic number of Carbon?', options: ['6', '8', '12', '14'], answer: 0 },
    { q: 'Which is an organic compound?', options: ['NaCl', 'CO₂', 'C₆H₁₂O₆', 'H₂O'], answer: 2 },
    { q: 'What is the pH of a neutral solution?', options: ['0', '7', '14', '1'], answer: 1 },
    { q: 'What is the molecular weight of H₂O?', options: ['16', '18', '20', '22'], answer: 1 },
    { q: 'Which element has symbol "Au"?', options: ['Silver', 'Aluminum', 'Gold', 'Argon'], answer: 2 },
    { q: 'What is the formula for methane?', options: ['CH₂', 'CH₃', 'CH₄', 'C₂H₄'], answer: 2 },
    { q: 'What is the main product of photosynthesis?', options: ['Carbon dioxide', 'Water', 'Glucose', 'Oxygen'], answer: 2 },
  ],
  bio: [
    { q: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Chloroplast'], answer: 2 },
    { q: 'Which organelle is responsible for photosynthesis?', options: ['Mitochondria', 'Chloroplast', 'Ribosome', 'Lysosome'], answer: 1 },
    { q: 'What is the basic unit of life?', options: ['Tissue', 'Organ', 'Cell', 'Molecule'], answer: 2 },
    { q: 'How many chromosomes does a human have?', options: ['23', '46', '48', '24'], answer: 1 },
    { q: 'What is the function of DNA?', options: ['Protein synthesis', 'Energy production', 'Genetic information storage', 'Cell division'], answer: 2 },
    { q: 'Which blood type is universal donor?', options: ['AB+', 'O+', 'O-', 'AB-'], answer: 2 },
    { q: 'What is the process of breaking down glucose called?', options: ['Photosynthesis', 'Respiration', 'Fermentation', 'Combustion'], answer: 1 },
  ],
  english: [
    { q: 'Identify the noun in the sentence: "She runs quickly."', options: ['She', 'runs', 'quickly', 'in'], answer: 0 },
    { q: 'Which word is an adjective?', options: ['Beautiful', 'Run', 'Quickly', 'Jump'], answer: 0 },
    { q: 'What is the opposite of "bright"?', options: ['Light', 'Dark', 'Clear', 'Shiny'], answer: 1 },
    { q: 'Identify the error: "He go to school every day."', options: ['He', 'go', 'school', 'every'], answer: 1 },
    { q: 'Which is a synonym for "happy"?', options: ['Sad', 'Joyful', 'Angry', 'Tired'], answer: 1 },
    { q: 'What is the past tense of "eat"?', options: ['Eated', 'Ate', 'Eating', 'Eats'], answer: 1 },
    { q: 'What punctuation mark is used at the end of a question?', options: ['Period', 'Comma', 'Question Mark', 'Exclamation'], answer: 2 },
  ],
};

export const SCORE_HISTORY = [
  { id: 's1', subject: 'Mathematics', test: 'Algebra Fundamentals', score: 85, total: 100, date: '2025-04-10', time: '28 min', rank: 142 },
  { id: 's2', subject: 'Physics', test: 'Mechanics & Motion', score: 72, total: 100, date: '2025-04-14', time: '29 min', rank: 287 },
  { id: 's3', subject: 'Computer Science', test: 'Data Structures Basics', score: 91, total: 100, date: '2025-04-18', time: '22 min', rank: 56 },
  { id: 's4', subject: 'Chemistry', test: 'Organic Chemistry – Reactions', score: 64, total: 100, date: '2025-04-22', time: '33 min', rank: 410 },
  { id: 's5', subject: 'Mathematics', test: 'Calculus – Limits & Derivatives', score: 78, total: 100, date: '2025-04-28', time: '43 min', rank: 201 },
  { id: 's6', subject: 'Biology', test: 'Cell Biology & Genetics', score: 88, total: 100, date: '2025-05-03', time: '27 min', rank: 98 },
];
